POST http://localhost:3048/api/troca/create
Content-Type: application/json

{

  "venda_id": 9,
  "compra_id": 1,
  "estoque_id": 1,
  "item_antigo_codBarra": "48BD",
  "item_novo_codBarra": "78GT",
  "motivo": "defeito",
  "descricaoTroca": "Tela trincada",
  "fornecedor_id": 1
}
