### ESTOQUE

### BUSCAR TODOS AS ESTOQUE
GET http://localhost:3048/api/estoque/all

### CADASTRAR NOVO ESTOQUE
### AO CADASTRAR UM ESTOQUE PELA PRIMEIRA VEZ, O VALOR DA QUANTIDADE PRECISA SER 0
POST http://localhost:3048/api/estoque/create
Content-Type: application/json

{
  "nome": "Motorola",
  "quantidade": 10,
  "fornecedor_id": 1,
  "categoria_id": 1
}

### BUSCAR ESTOQUE POR ID

GET http://localhost:3048/api/estoque/1
Content-Type: application/json


### BUSCAR ESTOQUE POR ID DA CATEGORIA

GET http://localhost:3048/api/estoque/AllCategoria/1
Content-Type: application/json

### BUSCAR ESTOQUE POR ID DO FORNECEDOR

GET http://localhost:3048/api/estoque/AllFornecedor/1
Content-Type: application/json


### DELETAR ESTOQUE POR ID

DELETE http://localhost:3048/api/estoque/delete/1
Content-Type: application/json

