### ESTOQUE

### BUSCAR TODOS AS ESTOQUE
GET http://localhost:3048/api/estoque/all

### CADASTRAR NOVO ESTOQUE
### AO CADASTRAR UM ESTOQUE PELA PRIMEIRA VEZ, O VALOR DA QUANTIDADE PRECISA SER 0
POST http://localhost:3048/api/estoque/create
Content-Type: application/json

{
  "nome": "Espátula",
  "quantidade": 0,
  "fornecedor_id": 1,
  "categoria_id": 1
}

### BUSCAR ESTOQUE POR ID

POST http://localhost:3048/api/estoque/get
Content-Type: application/json

{
  "id": 1
}

### BUSCAR ESTOQUE POR ID DA CATEGORIA

POST http://localhost:3048/api/estoque/AllCategoria
Content-Type: application/json

{
  "categoria_id": 2
}

### BUSCAR ESTOQUE POR ID DO FORNECEDOR

POST http://localhost:3048/api/estoque/AllFornecedor
Content-Type: application/json

{
  "fornecedor_id": 9
}

### DELETAR ESTOQUE POR ID

DELETE http://localhost:3048/api/estoque/delete
Content-Type: application/json

{
  "id": 1
}
