
### Marca

### BUSCAR TODOS AS Marca
GET http://localhost:3048/api/marca/all

### CADASTRAR NOVO OS

POST http://localhost:3048/api/marca/create
Content-Type: application/json

{
  "nome": "Samsung", 
  "categoria_id": 1
}

### BUSCAR Marca POR Categoria

GET http://localhost:3048/api/marca/getCategoria/1
Content-Type: application/json

### BUSCAR Marca POR ID

GET http://localhost:3048/api/marca/get/1
Content-Type: application/json


### DELETAR MARCA POR ID

DELETE http://localhost:3048/api/marca/delete
Content-Type: application/json

{
  "id": 1
}