################ OS

### BUSCAR TODOS AS OS

GET http://localhost:3048/api/venda/all?page=1&id=
### BUSCAR TOTAL DE CONSULTA POR MES

GET http://localhost:3048/api/venda/totalmes

### CADASTRAR NOVO OS

POST http://localhost:3048/api/venda/create
Content-Type: application/json

{
  "cliente_id": 1,
  "funcionario_id": 1,
  "QTparcelas": 2,
  "valorTotal": 48.00,
  "valorDesconto": 2,
  "valorPago": 0,
  "status":"Aguardando",
  "parcelas": [
    {
	  "tipoPagamento": "credito",
      "parcela": 1,
      "valorParcela": 24.00,
      "dataPagamento": "24/09/2024",
      "status": "pendente"
    },
	{
	  "tipoPagamento": "credito",
      "parcela": 2,
      "valorParcela": 24.00,
      "dataPagamento": "24/10/2024",
      "status": "pendente"
    }
  ],
  "produtos": [
    {
      "quantidade": 1,
      "id": 2
    }
  ]
}


### BUSCAR UMA OS POR ID

POST http://localhost:3048/api/os/get
Content-Type: application/json

{
  "id": 7
}

### DELETAR UMA OS POR ID

DELETE http://localhost:3048/api/venda/delete
Content-Type: application/json

{
  "id": 1
}

#### 

POST http://localhost:3048/api/venda/comissaoVendedor
Content-Type: application/json

{
  "page": 1,
  "limit": 5,
  "funcionario_id": 1,
  "data_inicio": "2024-09-05",
  "data_fim": "2024-09-05"
}