################ OS

### BUSCAR TODOS AS OS

GET http://localhost:3048/api/venda/all

### BUSCAR TOTAL DE CONSULTA POR MES

GET http://localhost:3048/api/venda/totalmes

### CADASTRAR NOVO OS

POST http://localhost:3048/api/venda/create
Content-Type: application/json

{
  "cliente_id": 2,
  "funcionario_id": 3,
  "QTparcelas": 1,
  "valorTotal": 48,
  "valorDesconto": 2,
  "status":"Aguardando",
  "parcelas": [
    {
      "parcela": 1,
      "valorParcela": 48,
      "dataPagamento": "24/09/2024",
      "status": "Pendente"
    }
  ],
  "produtos": [
    {
      "quantidade": 1,
      "id": 1
    }
  ]
}


### BUSCAR UMA OS POR ID

POST http://localhost:3048/api/os/get
Content-Type: application/json

{
  "id": 7
}

### DELETAR UMA OS POR ID

DELETE http://localhost:3048/api/os/delete
Content-Type: application/json

{
  "id": 4
}